version: '3.3'

services:
  wordpress:
    depends_on:
     - db
    image: wordpress:latest
    ports:
     - "8000:80"
    restart: always
    environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress
    volumes:
    - "./wp-content/plugins/:/var/www/html/wp-content/plugins/"
    - "./wp-content/themes/:/var/www/html/wp-content/themes/"
    - "./.htaccess:/var/www/html/.htaccess"

  db:
    image: mysql:5.7
    command: mysqld --sql_mode=""
    volumes:
     - ./.dbdata:/var/lib/mysql
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: wordpress
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress


